# Generated by scripts/brew-formula.sh in neoswarm/neosh — do not hand-edit.
class Neosh < Formula
  desc "Terminal-first agent workspace where every feature is a plugin"
  homepage "https://github.com/neoswarm/neosh"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.1/neosh-aarch64-apple-darwin.tar.gz"
      sha256 "8ce354fb5a6e68e242f3ef4359e0944ebdf6f50a33f42d6f427e2a458bad15d0"
    end
    on_intel do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.1/neosh-x86_64-apple-darwin.tar.gz"
      sha256 "b50c3689fb8cf6c3239df4345a123402162ae0eb9d0c692979e414d2673b041b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.1/neosh-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "22cb941394e403858a7011b60f904f04c97403d756f1d0b612f9c8d5105af010"
    end
    on_intel do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.1/neosh-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9fc8d557862d7c5f1cdb133da511ef28829105e579c98bebc162760524ca0137"
    end
  end

  def install
    bin.install "neosh"
  end

  test do
    assert_match "neosh #{version}", shell_output("#{bin}/neosh --version")
  end
end
