# Generated by scripts/brew-formula.sh in neoswarm/neosh — do not hand-edit.
class Neosh < Formula
  desc "Terminal-first agent workspace where every feature is a plugin"
  homepage "https://github.com/neoswarm/neosh"
  version "0.4.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.6/neosh-aarch64-apple-darwin.tar.gz"
      sha256 "cc8504455c5cc65aec4510faf2de96ca21431635d9ff1f2fd693f16d43ac38d6"
    end
    on_intel do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.6/neosh-x86_64-apple-darwin.tar.gz"
      sha256 "a0706793f42bdafa24cf700c48b32b67d43463122868e53f2ac353f4a063fc20"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.6/neosh-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "246ab2380dd60570583df6d0deaeeaf8757c708a8a6dd7bf0942bd6d950aabbe"
    end
    on_intel do
      url "https://github.com/neoswarm/neosh/releases/download/v0.4.6/neosh-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "558e5e1e3e172c7cc4558a9b223d7900299380739f4a3e975e374dabcd1a929d"
    end
  end

  def install
    bin.install "neosh"
  end

  test do
    assert_match "neosh #{version}", shell_output("#{bin}/neosh --version")
  end
end
